test:
  reports:
    mail_to: Setting.smtp_prod_reports_mailto
  out_of_stock_alert:
    mail_to: Setting.smtp_prod_out_of_stock_alert_mailto

development:
  reports:
    mail_to: Setting.smtp_prod_reports_mailto
  out_of_stock_alert:
    mail_to: Setting.smtp_prod_out_of_stock_alert_mailto

staging:
  reports:
    mail_to: "lachlan.sylvester@wi.com.au"
  out_of_stock_alert:
    mail_to: "lachlan.sylvester@wi.com.au"

production:
  reports:
    mail_to: Setting.smtp_prod_reports_mailto
  out_of_stock_alert:
    mail_to: Setting.smtp_prod_out_of_stock_alert_mailto
